name = "relics"

pages_build_output_dir = "./.svelte-kit/cloudflare/"

compatibility_date = "2024-11-06"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DATABASE"
database_name = "relics-db"
database_id = "71dcc9b9-852a-4fd3-b7a6-07b27d96336f"
