name = "relics"
account_id = "b1a7f24ebd961510d1d93a3c1838b782"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"
compatibility_date = "2024-11-27"
workers_dev = true

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DATABASE"
database_name = "relics-db"
database_id = "71dcc9b9-852a-4fd3-b7a6-07b27d96336f"
